language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

# Do py.test + coveralls
install:
  - pip install coveralls
script:
  - coverage run --source . -m py.test
  - coverage report -m

after_script:
  coveralls --verbose

# For now, Python 3 support is... :/
matrix:
  allow_failures:
    - python: 3.3
    - python: 3.4
    - pypy

